package com.example.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * PlanBlock Entity representing a scheduled block on the user's daily timeline.
 *
 * Each block is generated by the AI planner or confirmed by the user.
 * Deleting a Task automatically cascades and removes associated plan blocks.
 */
@Entity(
    tableName = "plan_blocks",
    foreignKeys = [
        ForeignKey(
            entity = Task::class,
            parentColumns = ["id"],
            childColumns = ["task_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["task_id"]), Index(value = ["plan_date"])]
)
data class PlanBlock(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    @ColumnInfo(name = "task_id")
    val taskId: Long? = null,
    @ColumnInfo(name = "plan_date")
    val planDate: String, // Local date format "yyyy-MM-dd"
    @ColumnInfo(name = "start_time")
    val startTime: String, // Format "HH:mm" (e.g. "09:00")
    @ColumnInfo(name = "end_time")
    val endTime: String, // Format "HH:mm" (e.g. "10:30")
    val type: String, // "task" | "focus" | "deadline"
    val nudge: String, // AI-generated encouraging nudge
    val accepted: Boolean = false
) {
    companion object {
        const val TYPE_TASK = "task"
        const val TYPE_FOCUS = "focus"
        const val TYPE_DEADLINE = "deadline"
    }
}
