package com.example.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Task Entity representing user and AI generated tasks and reminders.
 *
 * All timestamps are stored as UTC epoch milliseconds for consistency across timezones,
 * and converted to local device time only during UI presentation.
 *
 * @param id Unique primary key, auto-generated by SQLite.
 * @param title Short description of what needs to be done.
 * @param dueAt Exact due date/time as UTC epoch milliseconds, or null if unscheduled.
 * @param isDeadline True if this task represents a strict submission deadline.
 * @param remindBeforeMin How many minutes prior to [dueAt] the user wants an alarm (e.g. 30 min).
 * @param estimatedMin Estimated duration in minutes required to complete the task.
 * @param status Lifecycle status: "pending", "done", or "missed".
 * @param source Origin of task: "user" (created manually) or "ai" (parsed from chat).
 * @param createdAt Creation timestamp in UTC epoch milliseconds.
 */
@Entity(tableName = "tasks")
data class Task(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    @ColumnInfo(name = "due_at")
    val dueAt: Long? = null,
    @ColumnInfo(name = "is_deadline")
    val isDeadline: Boolean = false,
    @ColumnInfo(name = "remind_before_min")
    val remindBeforeMin: Int = 30,
    @ColumnInfo(name = "estimated_min")
    val estimatedMin: Int? = null,
    val status: String = STATUS_PENDING,
    val source: String = SOURCE_USER,
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
) {
    companion object {
        const val STATUS_PENDING = "pending"
        const val STATUS_DONE = "done"
        const val STATUS_MISSED = "missed"

        const val SOURCE_USER = "user"
        const val SOURCE_AI = "ai"
    }

    /**
     * Calculates the exact epoch millisecond when the AlarmManager notification should trigger.
     * Trigger time = dueAt - (remindBeforeMin * 60 * 1000).
     */
    val triggerTimeUtc: Long?
        get() = dueAt?.let { it - (remindBeforeMin.toLong() * 60L * 1000L) }
}
